package coffeepanda.apps.testing123

import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.github.kittinunf.fuel.core.Headers
import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.fuel.httpPost

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val sendRequestButton = findViewById<Button>(R.id.sendMessage)
        val showResponse = findViewById<TextView>(R.id.showChat)
        val user = findViewById<EditText>(R.id.User)
        val password = findViewById<EditText>(R.id.Password)
        val refresh = findViewById<Button>(R.id.RefreshChat)
        val msg = findViewById<EditText>(R.id.msg)
        sendRequestButton.setOnClickListener {
            "https://coffeepanda.co.uk/robloxia/chat.php".httpGet()
                .header(Headers.COOKIE to "PHPSESSID=abcd").response { _, response, _ ->
                    var cookies = response.headers.get("Set-Cookie").toString()
                    cookies = cookies.replace("[PHPSESSID=", "")
                    cookies = cookies.replace("; path=/]", "")
                    showResponse.text = cookies
                }
            var phpsessid = "PHPSESSID=" + showResponse.text
            var Username = user.text.toString()
            Username = Username.replace(" ", "%20")
            Username = Username.replace("!", "%21")
            Username = Username.replace("\"", "%22")
            Username = Username.replace("#", "%23")
            Username = Username.replace("\$", "%24")
            Username = Username.replace("%", "%25")
            Username = Username.replace("&", "%26")
            Username = Username.replace("\'", "%27")
            Username = Username.replace("(", "%28")
            Username = Username.replace(")", "%29")
            Username = Username.replace("*", "%2A")
            Username = Username.replace("+", "%2B")
            Username = Username.replace(",", "%2C")
            Username = Username.replace("-", "%2D")
            Username = Username.replace(".", "%2E")
            Username = Username.replace("/", "%2F")
            Username = Username.replace(":", "%3A")
            Username = Username.replace(";", "%3B")
            Username = Username.replace("<", "%3C")
            Username = Username.replace("=", "%3D")
            Username = Username.replace(">", "%3E")
            Username = Username.replace("?", "%3F")
            Username = Username.replace("@", "%40")
            Username = Username.replace("[", "%5B")
            Username = Username.replace("\\", "%5C")
            Username = Username.replace("]", "%5D")
            Username = Username.replace("^", "%5E")
            Username = Username.replace("_", "%5F")
            Username = Username.replace("`", "%60")
            Username = Username.replace("{", "%7B")
            Username = Username.replace("|", "%7C")
            Username = Username.replace("}", "%7D")
            Username = Username.replace("~", "%7E")
            var Pass = password.text.toString()
            Pass = Pass.replace(" ", "%20")
            Pass = Pass.replace("!", "%21")
            Pass = Pass.replace("\"", "%22")
            Pass = Pass.replace("#", "%23")
            Pass = Pass.replace("\$", "%24")
            Pass = Pass.replace("%", "%25")
            Pass = Pass.replace("&", "%26")
            Pass = Pass.replace("\'", "%27")
            Pass = Pass.replace("(", "%28")
            Pass = Pass.replace(")", "%29")
            Pass = Pass.replace("*", "%2A")
            Pass = Pass.replace("+", "%2B")
            Pass = Pass.replace(",", "%2C")
            Pass = Pass.replace("-", "%2D")
            Pass = Pass.replace(".", "%2E")
            Pass = Pass.replace("/", "%2F")
            Pass = Pass.replace(":", "%3A")
            Pass = Pass.replace(";", "%3B")
            Pass = Pass.replace("<", "%3C")
            Pass = Pass.replace("=", "%3D")
            Pass = Pass.replace(">", "%3E")
            Pass = Pass.replace("?", "%3F")
            Pass = Pass.replace("@", "%40")
            Pass = Pass.replace("[", "%5B")
            Pass = Pass.replace("\\", "%5C")
            Pass = Pass.replace("]", "%5D")
            Pass = Pass.replace("^", "%5E")
            Pass = Pass.replace("_", "%5F")
            Pass = Pass.replace("`", "%60")
            Pass = Pass.replace("{", "%7B")
            Pass = Pass.replace("|", "%7C")
            Pass = Pass.replace("}", "%7D")
            Pass = Pass.replace("~", "%7E")
            var loginInfo = "user=" + Username + "&pass=" + Pass
            "https://coffeepanda.co.uk/robloxia/sys/login.php".httpPost()
                .header(Headers.COOKIE to phpsessid).body(loginInfo.toString())
                .header(Headers.CONTENT_TYPE to "application/x-www-form-urlencoded")
                .response { _, _, result ->
                    var stringResult = result.toString()
                    if (stringResult.length == 21) {
                        refresh.setOnClickListener {
                            "https://coffeepanda.co.uk/robloxia/sys/chat.php?n=15".httpGet()
                                .header(Headers.COOKIE to phpsessid).body(loginInfo.toString())
                                .header(Headers.CONTENT_TYPE to "application/x-www-form-urlencoded")
                                .response { _, response, _ ->
                                    var chat = response.toString()
                                    chat = chat.replace("<b>", "")
                                    chat = chat.replace("</b>", "")
                                    chat = chat.replace("<span style=\"", "")
                                    chat = chat.replace(";\">", "")
                                    chat = chat.replace("color:29cc54", "")
                                    chat = chat.replace("color:#0067A5", "")
                                    chat = chat.replace("color:blue", "")
                                    chat = chat.replace("color:lightblue", "")
                                    chat = chat.replace("</span>:", ":")
                                    chat = chat.replace("</span>&", "&")
                                    chat = chat.replace("&nbsp;", " ")
                                    chat = chat.replace("<br/>", "\n")
                                    chat = chat.replace("color:darkgrey", "")
                                    chat = chat.replace("color:#66ccff", "")
                                    chat = chat.replace("Body : ", "")
                                    chat = chat.replace("Length : -1", "")
                                    chat = chat.replace("Headers : (18)", "")
                                    var gotheaders =
                                        response.headers.get("Cache-Control").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("X-Android-Selected-Protocol")
                                        .toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders =
                                        response.headers.get("X-Android-Response-Source").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders =
                                        response.headers.get("X-Android-Sent-Millis").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("X-Frame-Options").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Connection").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders =
                                        response.headers.get("Strict-Transport-Security").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Date").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("X-XSS-Protection").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Expires").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Server").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Referrer-Policy").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Content-Type").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders =
                                        response.headers.get("X-Content-Type-Options").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Pragma").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("X-Android-Received-Millis").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Vary").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    gotheaders = response.headers.get("Content-Length").toString()
                                    gotheaders = gotheaders.replace("[", "")
                                    gotheaders = gotheaders.replace("]", "")
                                    chat = chat.replace(gotheaders, "")
                                    chat = chat.replace(
                                        "<-- 200 https://coffeepanda.co.uk/robloxia/sys/chat.php?n=15",
                                        ""
                                    )
                                    chat = chat.replace("Response : OK", "")
                                    chat = chat.replace("timeout=5, max=99", "")
                                    chat = chat.replace("timeout=5, max=98", "")
                                    chat = chat.replace("timeout=5, max=97", "")
                                    chat = chat.replace("timeout=5, max=96", "")
                                    chat = chat.replace("timeout=5, max=95", "")
                                    chat = chat.replace("timeout=5, max=94", "")
                                    chat = chat.replace("timeout=5, max=100", "")
                                    chat = chat.replace("Content-Length :", "")
                                    chat = chat.replace("Vary :", "")
                                    chat = chat.replace("X-Android-Received-Millis :", "")
                                    chat = chat.replace("Pragma :", "")
                                    chat = chat.replace("X-Content-Type-Options :", "")
                                    chat = chat.replace("Content-Type :", "")
                                    chat = chat.replace("Referrer-Policy :", "")
                                    chat = chat.replace("Expires :", "")
                                    chat = chat.replace("Server :", "")
                                    chat = chat.replace("X-XSS-Protection :", "")
                                    chat = chat.replace("Date :", "")
                                    chat = chat.replace("Strict-Transport-Security :", "")
                                    chat = chat.replace("Connection :", "")
                                    chat = chat.replace("X-Frame-Options :", "")
                                    chat = chat.replace("X-Android-Sent-Millis :", "")
                                    chat = chat.replace("X-Android-Response-Source :", "")
                                    chat = chat.replace("X-Android-Selected-Protocol :", "")
                                    chat = chat.replace("Cache-Control :", "")
                                    chat = chat.replace(" :", "")
                                    chat = chat.replace("color:", "")
                                    chat = "\n\n" + chat
                                    showResponse.text = chat
                                    sendRequestButton.setOnClickListener {
                                        var sendMsg = "message=" + msg.text
                                        "https://coffeepanda.co.uk/robloxia/sys/chat.php?n=15".httpPost()
                                            .header(Headers.COOKIE to phpsessid)
                                            .body(sendMsg.toString())
                                            .header(Headers.CONTENT_TYPE to "application/x-www-form-urlencoded")
                                            .response { _, _, _ ->
                                            }
                                        "https://coffeepanda.co.uk/robloxia/sys/chat.php?n=15".httpGet()
                                            .header(Headers.COOKIE to phpsessid)
                                            .body(loginInfo.toString())
                                            .header(Headers.CONTENT_TYPE to "application/x-www-form-urlencoded")
                                            .response { _, response, _ ->
                                                var chat = response.toString()
                                                chat = chat.replace("<b>", "")
                                                chat = chat.replace("</b>", "")
                                                chat = chat.replace("<span style=\"", "")
                                                chat = chat.replace(";\">", "")
                                                chat = chat.replace("color:29cc54", "")
                                                chat = chat.replace("color:#0067A5", "")
                                                chat = chat.replace("color:blue", "")
                                                chat = chat.replace("color:lightblue", "")
                                                chat = chat.replace("</span>:", ":")
                                                chat = chat.replace("</span>&", "&")
                                                chat = chat.replace("&nbsp;", " ")
                                                chat = chat.replace("<br/>", "\n")
                                                chat = chat.replace("color:darkgrey", "")
                                                chat = chat.replace("color:#66ccff", "")
                                                chat = chat.replace("Body : ", "")
                                                chat = chat.replace("Length : -1", "")
                                                chat = chat.replace("Headers : (18)", "")
                                                var gotheaders =
                                                    response.headers.get("Cache-Control").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-Android-Selected-Protocol")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-Android-Response-Source")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-Android-Sent-Millis")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders = response.headers.get("X-Frame-Options")
                                                    .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Connection").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Strict-Transport-Security")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders = response.headers.get("Date").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-XSS-Protection")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Expires").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Server").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders = response.headers.get("Referrer-Policy")
                                                    .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Content-Type").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-Content-Type-Options")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("Pragma").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders =
                                                    response.headers.get("X-Android-Received-Millis")
                                                        .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders = response.headers.get("Vary").toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                gotheaders = response.headers.get("Content-Length")
                                                    .toString()
                                                gotheaders = gotheaders.replace("[", "")
                                                gotheaders = gotheaders.replace("]", "")
                                                chat = chat.replace(gotheaders, "")
                                                chat = chat.replace(
                                                    "<-- 200 https://coffeepanda.co.uk/robloxia/sys/chat.php?n=15",
                                                    ""
                                                )
                                                chat = chat.replace("Response : OK", "")
                                                chat = chat.replace("timeout=5, max=99", "")
                                                chat = chat.replace("timeout=5, max=98", "")
                                                chat = chat.replace("timeout=5, max=97", "")
                                                chat = chat.replace("timeout=5, max=96", "")
                                                chat = chat.replace("timeout=5, max=95", "")
                                                chat = chat.replace("timeout=5, max=94", "")
                                                chat = chat.replace("timeout=5, max=100", "")
                                                chat = chat.replace("Content-Length :", "")
                                                chat = chat.replace("Vary :", "")
                                                chat =
                                                    chat.replace("X-Android-Received-Millis :", "")
                                                chat = chat.replace("Pragma :", "")
                                                chat = chat.replace("X-Content-Type-Options :", "")
                                                chat = chat.replace("Content-Type :", "")
                                                chat = chat.replace("Referrer-Policy :", "")
                                                chat = chat.replace("Expires :", "")
                                                chat = chat.replace("Server :", "")
                                                chat = chat.replace("X-XSS-Protection :", "")
                                                chat = chat.replace("Date :", "")
                                                chat =
                                                    chat.replace("Strict-Transport-Security :", "")
                                                chat = chat.replace("Connection :", "")
                                                chat = chat.replace("X-Frame-Options :", "")
                                                chat = chat.replace("X-Android-Sent-Millis :", "")
                                                chat =
                                                    chat.replace("X-Android-Response-Source :", "")
                                                chat = chat.replace(
                                                    "X-Android-Selected-Protocol :",
                                                    ""
                                                )
                                                chat = chat.replace("Cache-Control :", "")
                                                chat = chat.replace(" :", "")
                                                chat = chat.replace("color:", "")
                                                chat = "\n\n" + chat
                                                showResponse.text = chat
                                            }
                                    }
                                }
                        }
                    }
                }
        }
    }
}